"""sync models: add CAPA.description and fields

Revision ID: 6506fa356f9c
Revises: fe9a721649bd
Create Date: 2025-08-19 14:08:39.407744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6506fa356f9c'
down_revision = 'fe9a721649bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=False))

    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    with op.batch_alter_table('capa', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
